name: food_classifier_app
description: A food classification app using live camera feed
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+5
  permission_handler: ^11.0.1
  http: ^1.3.0
  image: ^4.5.4
  path_provider: ^2.1.2
  tflite_flutter: ^0.10.4
  # Added dependencies
  mysql1: ^0.20.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  path: ^1.9.1
  image_picker: ^1.0.7  # Added for gallery image selection
  lottie: ^3.3.1  # Updated to a compatible version
  fl_chart: ^0.65.0  # Added for charts and data visualization
  syncfusion_flutter_gauges: ^29.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/models/
    - assets/images/
    - assets/lottie/  # Added for Lottie animation files
